##### Server

server:
  port: 8081

##### Eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

##### Spring

spring:
  application:
    name: teams-and-players-service
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5433}/${DB_NAME:teams_and_players_base}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}