##### Server

server:
  port: 8080

##### Actuator

management:
  endpoints:
    web:
      exposure:
        include: '*'

##### Eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

##### Zuul

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    teams-and-players-service:
      path: /teams-and-players/**
      serviceId: teams-and-players-service
      stripPrefix: true
    fee-service:
      path: /fee/**
      serviceId: fee-service
      stripPrefix: true

##### Spring

spring:
  application:
    name: gateway-service