server:
  port: ${EDUREKA_PORT:8761}

eureka:
  instance:
    hostname: ${EDUREKA_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  server:
    wautTineInSmWhenSyncEmpty: 0