server:
  port: ${EUREKA_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:${EUREKA_PORT:8761}/eureka
  server:
    wautTineInSmWhenSyncEmpty: 0