##### Server

server:
  port: 8082

##### Eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_URL:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    hostname: ${HOST:localhost}

##### Spring

spring:
  application:
    name: fee-service
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5434}/${DB_NAME:fee_base}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
